details:
  namespace: student19-bookinfo-uat
  image: ghcr.io/fyefee/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student19/details(/|$)(.*)"
  serviceType: ClusterIP